auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  max_outstanding_per_tenant: 4096

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

querier:
  max_concurrent: 16

limits_config:
  max_query_parallelism: 32
  split_queries_by_interval: 15m
  reject_old_samples: true
  reject_old_samples_max_age: 8760h
  max_streams_per_user: 0
  max_global_streams_per_user: 0
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128

ingester:
  max_transfer_retries: 0

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false
