[global]
   workgroup = WORKGROUP
   server role = standalone server
   map to guest = Bad User
   usershare allow guests = yes
   log level = 1 auth:3 smb:2
   log file = /var/log/samba/smbd.log
   max log size = 10240
   vfs objects = full_audit
   full_audit:prefix = %u|%I|%S
   full_audit:success = open pread
   full_audit:failure = none
   full_audit:facility = local7
   full_audit:priority = notice

[Operations]
   path = /srv/samba/Operations
   browseable = yes
   read only = yes
   guest ok = yes
   force user = nobody

[Backups]
   path = /srv/samba/Backups
   browseable = yes
   read only = yes
   guest ok = yes
   force user = nobody

[Docs]
   path = /srv/samba/Docs
   browseable = yes
   read only = yes
   guest ok = yes
   force user = nobody
